### ISSUE TITLE
About ctest

### ISSUE THREAD

**Issue by Nakamotto** [Microsoft/SealPIR#16]
After `cmake .`,i encounter the below error when `ctest .` 
![image](https://user-images.githubusercontent.com/86862596/162979983-4b1d5988-65f0-4a91-a923-3b786e7ba72a.png)
Thanks for your time in advance! :)

**Comment by sga001** [comment]
That's happening because you haven't compiled sealpir yet.

Try this:

```
cmake .
make
ctest .
```

(I think you skipped the middle step).

If this doesn't work, I wonder if it is a path issue on Windows. I tested it on:

(1) Ubuntu
(2) Linux subsystem for windows
(3) OS X

And it was fine on all 3. I have not tested on Windows by itself, so it is possible ctest is off somehow. You can always run the tests manually. The binaries are in `bin/<test name>`

**Comment by Nakamotto** [comment]
Yes, I run it on windows.
As you say, I manually run the binaries successfully.
Thanks! :)
