### ISSUE TITLE
About Test 

### ISSUE THREAD

**Issue by MDGBDGMG** [Microsoft/SealPIR#22]
hello， I ran `ctest .`  and got that:
![image](https://user-images.githubusercontent.com/45615979/209074049-f8bd819f-aa18-4a7f-adbe-2765dcd12c70.png)

I waited for a long time, but there was no change
pls help me, thank you!

**Comment by sga001** [comment]
It works, it's just slow because it is using a random number generator instead of a PRG.

I have addressed it in my pull request, or you can clone this repo which has the latest: https://github.com/sga001/sealpir.

In any case, know that even with the changes I pushed test 3 takes about 130 seconds in my laptop, and test 6 also takes like 130 seconds to complete.
