### ISSUE TITLE
A question about plaintext encoding.

### ISSUE THREAD

**Issue by most-vegetable-player** [Microsoft/SealPIR#28]
Hi! According to the paper, the client encodes his desired query _i_ into a  monomial as follows : 
![image](https://github.com/microsoft/SealPIR/assets/82452826/7396f2ed-ca24-4d06-82ea-8244acd47858)
![image](https://github.com/microsoft/SealPIR/assets/82452826/bdccc480-a29f-4911-bda4-866937a843fc)
But I can't find in which part of this code the encoding process is implemented. 
Looking forward to a reply. Thanks.

**Comment by sga001** [comment]
It's here:

https://github.com/microsoft/SealPIR/blob/12f6c0ff34ed3e4da47072544efb0b44bb745e4b/src/pir_client.cpp#L72

The code is a little more complicated because we need to generate a query for every dimension.

**Comment by most-vegetable-player** [comment]
Thanks, I get it. 
I run the code, and I print the encoded query pt by using "cout << pt.to_string()" after this line: 
https://github.com/microsoft/SealPIR/blob/12f6c0ff34ed3e4da47072544efb0b44bb745e4b/src/pir_client.cpp#L99-L100
The output is not a monomial with coefficient 1 but a monomial with coefficient 1F2141 in hex (2040129 in dec). 
Does this mean that the coefficient of the monomial does not necessarily have to be 1?

**Comment by sga001** [comment]
Ah, this is because we are doing a little trick. In the paper (figure 3) we say the server has to do the following 3 operations: 

14: inverse ← m−1 (mod t)
15: for j = 0 to n − 1 do
16: oj ← ciphertexts[j] · inverse

Turns out, we can just have the client compute this inverse directly on the plaintext polynomial before encrypting it, which has the same effect and avoids the expense of that plaintext-ciphertext multiplication at the server. 

So this basically boils down to creating the monomial 1x^i and then multiplying it by inverse of t; or equivalently, just setting the coefficient to be the inverse of t, which is precisely what you see above.
